### ISSUE TITLE
Manage role-groups & tenants

### ISSUE THREAD

**Issue by weedkiller** [Swastika-IO/sio.core#59]
While roles exist, they are too broad in ASP.

Swastika is the final answer, and is simply awesome, and could use some role-groups (sub groups of roles) & tenant management.
For e.g.

East Coast Mgrs can only see data of East Cost Employees
West Mgrs can only see salaries of West Coast Employees (User group)
HQ mgrs, can see all

**Comment by Smilefounder** [comment]
Thanks @weedkiller May I assumed that this is not an issue?

**Comment by weedkiller** [comment]
Yes its not an issue, feature request 😃

**Comment by Smilefounder** [comment]
Hi @weedkiller , this feature already exists, sorry that we don't have enough time to develop the full document yet. You can play around with the user section in the admin panel.

**Comment by Smilefounder** [comment]
@weedkiller FYI please access the following youtube channel for the easier to play with the CMS :)
https://www.youtube.com/watch?v=OuFNELcb-TE&list=PLlrIpXXu0w7yL6WywQRQphemZKUO0yBNB&index=5
