### ISSUE TITLE
demo error on s

### ISSUE THREAD

**Issue by weedkiller** [Swastika-IO/sio.core#60]
tried to run a demo..

![image](https://user-images.githubusercontent.com/21086190/48248226-76248480-e3c4-11e8-9402-ae0b3bdad4a4.png)

**Comment by Smilefounder** [comment]
> tried to run a demo..
> 
> ![image](https://user-images.githubusercontent.com/21086190/48248226-76248480-e3c4-11e8-9402-ae0b3bdad4a4.png)

Hi @weedkiller , the main site is fixed. Please have a look and let us know if you have any other concern.
