### ISSUE TITLE
Solution error

### ISSUE THREAD

**Issue by DmitryAA** [Swastika-IO/sio.core#61]
Please, append Sio.Heart and Sio.Identity projects to source code repository. This projects was not loaded to source code solution.

**Comment by Smilefounder** [comment]
Hi @DmitryAA sorry for have you found the issue. We are in the process for clean up all source code now. Will keep you posted when it is done.

**Comment by DmitryAA** [comment]
Thank you for annswer. Сan your made goods subcategories for cms goods, if is it possible?

**Comment by Smilefounder** [comment]
@DmitryAA : FYI, you can take a look on this quick tutorial video https://youtu.be/GiKp7J3Vbv0

**Comment by DmitryAA** [comment]
Thank you for video. It is very good information for me. Can you restoring  main cms site https://swastika.io working.

**Comment by Smilefounder** [comment]
> Thank you for video. It is very good information for me. Can you restoring main cms site https://swastika.io working.

yes, the main cms site is now working. thanks for your information.
