### ISSUE TITLE
Build instructions incomplete

### ISSUE THREAD

**Issue by jakenuts** [Swastika-IO/sio.core#62]
The build instructions in the readme file should probably be:

```
mkdir mixcore
cd mixcore

git clone https://github.com/Swastika-IO/sio.heart.git
git clone https://github.com/Swastika-IO/sio.identity.git
git clone https://github.com/Swastika-IO/sio.core.git

cd sio.core/src/sio.cms.web

**npm install**  
gulp build
**dotnet restore** 
dotnet bundle
dotnet build
dotnet run
```
open browser to https://localhost:5001/

(still need to figure out how to resolve the db missing issue)

**Comment by Smilefounder** [comment]
@nhathoang989 @Sint94 Please help double check

**Comment by Smilefounder** [comment]
@jakenuts please replace all content inside "appsettings.json" file with "{}" and then let us know if you still facing any issues.
