### ISSUE TITLE
Demo Site and download still have errors

### ISSUE THREAD

**Issue by weedkiller** [Swastika-IO/sio.core#63]
hello, please see picture, tried latest and still have error.

![image](https://user-images.githubusercontent.com/21086190/50388348-78773f80-06e1-11e9-96de-8b6d2b2feed6.png)

I believe you have every right to choose the name you like, and Swatika is actually a very pretty word orginally from a different purpose, 🤗 

1. BTW, are you planning to have a robust plugin dev architecture
2. in place upgrades

**Comment by Smilefounder** [comment]
Hi @weedkiller, really happy to receive your valued feedback as always.
FYI, the Swastika is also really meaningful to me and our team as well. So we don't have any plan to change it :). We just clean up the coding, naming convention to make it more robust for developers. The project name still "Swastika I/O" as it is.

Besides that, we have received a lot of people feedback about the project name. So we did think a bit and have another plan for those group of people is using another project name with the same source coded with Swastika I/O. We just want everyone to have more choices and decision to choose and use our best with freedom and happiness.

For sure, it will take our team double times to maintenance both. But I promise with you that, both projects will have our best at the same meaning.

For plugin plan, as dotnet core doesn't have the best solution out of the box at the moment. So we are holding this plan a bit and focusing on the first production release of Swastika I/O. Will keep you posted in this later.

For upgrades plan, we have planned on this one at the very beginning of the project. As this is the main reason for keeping our CMS alive in the future as well. We did plan and structured the DB, source code really careful so it will be less upgrade required to the main core later in the future. But we do have the solution for the upgraded core as well.
